## Isabelle/jEdit LLM Suggestions plugin properties
##

#identification
plugin.isabelle.llm_suggestions.LLM_Suggestions_Plugin.name=LLM Suggestions
plugin.isabelle.llm_suggestions.LLM_Suggestions_Plugin.author=Maximilian Schaeffeler
plugin.isabelle.llm_suggestions.LLM_Suggestions_Plugin.version=0.1
plugin.isabelle.llm_suggestions.LLM_Suggestions_Plugin.description=Isabelle/jEdit LLM Suggestions panel plugin

#system parameters
plugin.isabelle.llm_suggestions.LLM_Suggestions_Plugin.activate=startup
plugin.isabelle.llm_suggestions.LLM_Suggestions_Plugin.usePluginHome=false

#dependencies
plugin.isabelle.llm_suggestions.LLM_Suggestions_Plugin.depend.0=plugin isabelle.jedit_main.Plugin 11.2

#menu actions and dockables
plugin.isabelle.llm_suggestions.LLM_Suggestions_Plugin.menu.label=LLM Suggestions
plugin.isabelle.llm_suggestions.LLM_Suggestions_Plugin.menu=llm-suggestions-dockable
llm-suggestions-dockable.label=LLM Suggestions Panel
llm-suggestions-dockable.title=LLM Suggestions
llm-suggestions-dockable.dock-position=right
