title = LLM Suggestions
module=$JEDIT_SETTINGS/jars/llm_suggestions_plugin.jar
requirements = \
  env:ISABELLE_SCALA_JAR \
  env:JEDIT_JARS
sources = \
  src/proof_context_parser.scala \
  src/llm_providers.scala \
  src/llm_suggestions_dockable.scala \
  src/llm_suggestions_plugin.scala
resources = \
  dockables.xml \
  plugin.props
